/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileWriterRouteImport } from './routes/profile.writer'
import { Route as ProfileReaderRouteImport } from './routes/profile.reader'
import { Route as ReadStoryIdRouteImport } from './routes/read.story.$id'
import { Route as ReadPoemIdRouteImport } from './routes/read.poem.$id'
import { Route as ReadNovelIdRouteImport } from './routes/read.novel.$id'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWriterRoute = ProfileWriterRouteImport.update({
  id: '/profile/writer',
  path: '/profile/writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileReaderRoute = ProfileReaderRouteImport.update({
  id: '/profile/reader',
  path: '/profile/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadStoryIdRoute = ReadStoryIdRouteImport.update({
  id: '/read/story/$id',
  path: '/read/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadPoemIdRoute = ReadPoemIdRouteImport.update({
  id: '/read/poem/$id',
  path: '/read/poem/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadNovelIdRoute = ReadNovelIdRouteImport.update({
  id: '/read/novel/$id',
  path: '/read/novel/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/write': typeof WriteRoute
  '/profile/reader': typeof ProfileReaderRoute
  '/profile/writer': typeof ProfileWriterRoute
  '/read/novel/$id': typeof ReadNovelIdRoute
  '/read/poem/$id': typeof ReadPoemIdRoute
  '/read/story/$id': typeof ReadStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/write': typeof WriteRoute
  '/profile/reader': typeof ProfileReaderRoute
  '/profile/writer': typeof ProfileWriterRoute
  '/read/novel/$id': typeof ReadNovelIdRoute
  '/read/poem/$id': typeof ReadPoemIdRoute
  '/read/story/$id': typeof ReadStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/write': typeof WriteRoute
  '/profile/reader': typeof ProfileReaderRoute
  '/profile/writer': typeof ProfileWriterRoute
  '/read/novel/$id': typeof ReadNovelIdRoute
  '/read/poem/$id': typeof ReadPoemIdRoute
  '/read/story/$id': typeof ReadStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/write'
    | '/profile/reader'
    | '/profile/writer'
    | '/read/novel/$id'
    | '/read/poem/$id'
    | '/read/story/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/write'
    | '/profile/reader'
    | '/profile/writer'
    | '/read/novel/$id'
    | '/read/poem/$id'
    | '/read/story/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/write'
    | '/profile/reader'
    | '/profile/writer'
    | '/read/novel/$id'
    | '/read/poem/$id'
    | '/read/story/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  WriteRoute: typeof WriteRoute
  ProfileReaderRoute: typeof ProfileReaderRoute
  ProfileWriterRoute: typeof ProfileWriterRoute
  ReadNovelIdRoute: typeof ReadNovelIdRoute
  ReadPoemIdRoute: typeof ReadPoemIdRoute
  ReadStoryIdRoute: typeof ReadStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/writer': {
      id: '/profile/writer'
      path: '/profile/writer'
      fullPath: '/profile/writer'
      preLoaderRoute: typeof ProfileWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/reader': {
      id: '/profile/reader'
      path: '/profile/reader'
      fullPath: '/profile/reader'
      preLoaderRoute: typeof ProfileReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/story/$id': {
      id: '/read/story/$id'
      path: '/read/story/$id'
      fullPath: '/read/story/$id'
      preLoaderRoute: typeof ReadStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/poem/$id': {
      id: '/read/poem/$id'
      path: '/read/poem/$id'
      fullPath: '/read/poem/$id'
      preLoaderRoute: typeof ReadPoemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/novel/$id': {
      id: '/read/novel/$id'
      path: '/read/novel/$id'
      fullPath: '/read/novel/$id'
      preLoaderRoute: typeof ReadNovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  WriteRoute: WriteRoute,
  ProfileReaderRoute: ProfileReaderRoute,
  ProfileWriterRoute: ProfileWriterRoute,
  ReadNovelIdRoute: ReadNovelIdRoute,
  ReadPoemIdRoute: ReadPoemIdRoute,
  ReadStoryIdRoute: ReadStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
